/**
 * @fileoverview Registro central de iconos Lucide que la aplicación usa.
 *
 * Este archivo es la única entrada al paquete `lucide-react`. Cualquier icono
 * nuevo que un componente necesite debe añadirse AQUÍ (para que el wrapper
 * `<Icon />` lo pueda resolver y para que el catálogo completo sea auditable).
 *
 * Los imports son nominales para no romper el tree-shaking de Vite; el wrapper
 * `<Icon />` hace lookup O(1) por nombre.
 *
 * Si más adelante añadimos un icono aquí, conviene también documentarlo en
 * `frontend/docs/01-PATRONES-DISENO.md` en la sección "Icon system".
 *
 * @module components/ui/iconRegistry
 */

import {
  Activity,
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowRightLeft,
  ArrowUp,
  ArrowUpDown,
  ArrowUpRight,
  Award,
  BarChart3,
  Bell,
  Brain,
  Calendar,
  CalendarClock,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  CreditCard,
  Download,
  Edit,
  Edit2,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Flag,
  FolderOpen,
  Gamepad2,
  Gauge,
  GraduationCap,
  Hand,
  Hash,
  Home,
  IdCard,
  Image,
  ImageIcon,
  Info,
  Landmark,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  Lightbulb,
  Link2,
  LinkIcon,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Map,
  Menu,
  MessageSquare,
  Minus,
  MoreVertical,
  Music,
  Palette,
  Pause,
  PawPrint,
  Pencil,
  Play,
  Plus,
  PlusCircle,
  Printer,
  RefreshCw,
  RotateCcw,
  Save,
  Scale,
  School,
  Search,
  Settings,
  Shapes,
  Shield,
  ShieldCheck,
  ShieldX,
  Shuffle,
  Sparkles,
  Star,
  Target,
  ThumbsUp,
  Timer,
  Trash2,
  TrendingDown,
  TrendingUp,
  Trophy,
  Upload,
  Usb,
  User,
  UserCheck,
  UserPlus,
  UserX,
  Users,
  Volume2,
  VolumeX,
  Wand2,
  Wifi,
  WifiOff,
  X,
  XCircle,
  Zap,
  ZapOff
} from 'lucide-react';

/**
 * Mapa canonical name → React component.
 * Los aliases comunes (`ImageIcon` → `Image`, `MapIcon` → `Map`, `LinkIcon` →
 * `Link2`) se registran en ambas formas para que el wrapper acepte cualquiera
 * de los nombres que el proyecto ya usa en su código existente.
 */
export const ICON_REGISTRY = Object.freeze({
  Activity,
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowRightLeft,
  ArrowUp,
  ArrowUpDown,
  ArrowUpRight,
  Award,
  BarChart3,
  Bell,
  Brain,
  Calendar,
  CalendarClock,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  CreditCard,
  Download,
  Edit,
  Edit2,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Flag,
  FolderOpen,
  Gamepad2,
  Gauge,
  GraduationCap,
  Hand,
  Hash,
  Home,
  IdCard,
  Image,
  ImageIcon,
  Info,
  Landmark,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  Lightbulb,
  Link2,
  LinkIcon,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Map,
  // Alias reconocido: muchos archivos importan `Map as MapIcon` para evitar el
  // choque con el constructor global `Map`. Registramos el alias explícitamente
  // para que la migración sea un simple search-and-replace sin quebraderos.
  MapIcon: Map,
  Menu,
  MessageSquare,
  Minus,
  MoreVertical,
  Music,
  Palette,
  Pause,
  PawPrint,
  Pencil,
  Play,
  Plus,
  PlusCircle,
  Printer,
  RefreshCw,
  RotateCcw,
  Save,
  Scale,
  School,
  Search,
  Settings,
  Shapes,
  Shield,
  ShieldCheck,
  ShieldX,
  Shuffle,
  Sparkles,
  Star,
  Target,
  ThumbsUp,
  Timer,
  Trash2,
  TrendingDown,
  TrendingUp,
  Trophy,
  Upload,
  Usb,
  User,
  UserCheck,
  UserPlus,
  UserX,
  Users,
  Volume2,
  VolumeX,
  Wand2,
  Wifi,
  WifiOff,
  X,
  XCircle,
  Zap,
  ZapOff
});

/**
 * Devuelve el nombre canónico (nombre real de Lucide) para un icono del registry.
 * Útil al auditar qué iconos se usan realmente. No se consume desde los
 * componentes; es sólo para tooling / docs.
 *
 * @returns {string[]}
 */
export const listRegisteredIconNames = () =>
  Object.keys(ICON_REGISTRY).sort((a, b) => a.localeCompare(b));

